### ISSUE TITLE
I meet a problem,I don't know how to solve.

### ISSUE THREAD

**Issue by xuethe** [zhejz/HPTR#1]
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])

**Comment by xuethe** [comment]
wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
Error executing job with overrides: ['trainer=womd', 'model=scr_womd', 'datamodule=h5_womd', 'loggers.wandb.name=hptr_womd', 'loggers.wandb.project=hptr_train', 'loggers.wandb.entity=YOUR_ENTITY', 'datamodule.data_dir=/mnt/workspace/HPTR/DT']

**Comment by xuethe** [comment]
I hope the author can give an example to show more clear directory structure of original dataset and process dataset

**Comment by zhejz** [comment]
We use wandb for logging, for that you need to register a wandb account and change `loggers.wandb.entity=YOUR_ENTITY ` to your wandb entity.

**Comment by zhejz** [comment]
About the directory structure of original dataset and process dataset. Check out the `bash/pack_h5.sh` file. The `out-dir` is the processed dataset while the `data-dir` is the original dataset.
In the `out-dir` you should have three files `testing.h5`,  `training.h5` and  `validation.h5` after you run the `pack_h5.sh`
In the `data-dir` you should have three folders `testing`, `training` and `validation` after you download from the dataset. These three folders contain the tfrecords.
