### ISSUE TITLE
There was an error trying to execute run.py

### ISSUE THREAD

**Issue by Joys001** [zhejz/HPTR#2]
error content:
ret = run_job(
Seed set to 2023
Error executing job with overrides: []
Error in call to target 'data_modules.data_h5_womd.DataH5womd':
TypeError("unsupported operand type(s) for |: 'dict' and 'dict'")
full_key: datamodule

**Comment by zhejz** [comment]
Seems like an environment problem, the `|` operand for `dict` is only supported in newer python versions. Please make sure you have the correct conda env.
