### ISSUE TITLE
how many epochs to run to reproduce your results on waymo?

### ISSUE THREAD

**Issue by SixingHu** [zhejz/HPTR#4]
Thank u for open sourcing your great work.

May i know how many epochs are needed to reproduce your results on waymo?
In your HPTR/configs/trainer/womd.yaml file, what hyper parameter should be set?
max_epochs: null
min_epochs: null

Thank you in advance for you kind help!

**Comment by zhejz** [comment]
Hi, you can find the training details in Sec 4.1 in our paper. Our final models are trained for 120 epochs for WOMD
and 150 epochs for AV2.

**Comment by SixingHu** [comment]
Thank you for your kind help!
