### ISSUE TITLE
pack_h5_av2.py

### ISSUE THREAD

**Issue by jakubmoscinski** [zhejz/HPTR#5]
Hello there,
I am afraid there is some bug over there. I would like to kindly ask you for support

```
(hptr_av2) root@workstation:~/autodl-tmp/HPTR-main# python3 src/pack_h5_av2.py --dataset=train --out-dir=/root/autodl-tmp/h5_av2_hptr/ --data-dir=/root/autodl-tmp/av2_motion/
  0%|                                                                                                                                                                                 | 0/199908 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/autodl-tmp/HPTR-main/src/pack_h5_av2.py", line 342, in <module>
    main()
  File "/root/autodl-tmp/HPTR-main/src/pack_h5_av2.py", line 233, in main
    scenario_folder / f"scenario_{scenario_folder.name}.parquet", n_step
UnboundLocalError: local variable 'n_step' referenced before assignment
```

Best wishes

**Comment by zhejz** [comment]
It should be `--dataset=training` rather than `--dataset=train`. And also please make sure the correct conda environment is used.

**Comment by jakubmoscinski** [comment]
Thank you for your quick response.

When `--dataset=training` it appears to miss the training directory entirely:

```
(hptr_av2) root@workstation:~/autodl-tmp/HPTR-main# python3 src/pack_h5_av2.py --dataset=training --out-dir=/root/autodl-tmp/h5_av2_hptr/ --data-dir=/root/autodl-tmp/av2_motion/
0it [00:00, ?it/s]
n_pl_max: 0, n_agent_max: 0
n_agent_sim: 0, n_agent_no_sim: 0
```

Following the specs for AV2 the env is set to `hptr_av2`

Best

**Comment by zhejz** [comment]
Could you please check if the AV2 dataset has been correctly downloaded? You can check line 223 and print out the `scenario_list`, which is probably empty in your case. It should be filled with paths to scenario folders

**Comment by jakubmoscinski** [comment]
I have downloaded the whole dataset in 2 possible ways:

1) `wget https://s3.amazonaws.com/argoverse/datasets/av2/tars/motion-forecasting/train.tar` (train.tar / test.tar / val.tar)
2) And follwoing the instructions from `https://argoverse.github.io/user-guide/getting_started.html#download-the-datasets`

In both cases the result is the same:

`tree av2_motion/ -L 1`
```
av2_motion/
|-- test
|-- train
`-- val
```

First 15 files from train:

```
~/autodl-tmp/av2_motion/train# ls -1 | head -n 15
0000b0f9-99f9-4a1f-a231-5be9e4c523f7
0000b6ab-e100-4f6b-aee8-b520b57c0530
0001b567-b7ac-4a91-b4fe-6132e4b81884
0001f576-0552-49c9-9ce2-8c47411a088e
0001fe2b-a3c8-4cdf-a712-6b65a17ca316
0002cd4c-d011-4f89-84e4-5a042007f034
00037cc8-2b41-49cb-a781-f07c39328dff
0003904f-371d-4544-8712-5f4eff74ef91
0003d1d1-ae8b-432c-b365-76ecd41867f9
0003e31e-8142-47af-9215-b8a306a31bc9
000410c1-84d8-43a6-b6e8-34616cc1543f
00052182-d782-4196-a025-a9916aaae4d6
00052803-b0e6-4d8a-8abe-d8870d7c4132
00055ac5-75e4-41f7-a783-31dd49fca4be
0005dd1d-53ee-4db2-be95-a09e64d78b61
```

Assuming that the `dataset` can be set to `train` it appears to start processing. However at some point it raises an error `UnboundLocalError: local variable 'n_step' referenced before assignment`

 `| 0/199908 [00:00<?, ?it/s]Traceback (most recent call last):` This part also confirms that it sees the files to be processed

**Comment by roydenwa** [comment]
@zhejz @jakubmoscinski I had the same issues. The folder names for AV2 are different from Waymo (train instead of training). So, renaming the folders to training, validation and testing solves the first issue. The second issue is the same as [here](https://github.com/zhejz/HPTR/issues/3) (setting agent/dest to 0 solved it in my case). 
Btw, great work @zhejz!

**Comment by jakubmoscinski** [comment]
It works! 
Thank you very much guys.

Just to make sure,

`In pack_h5.py`

Line 783

```
episode_reduced["agent/dest"][i] = find_dest(
                episode_reduced["agent/type"][i],
                episode_reduced["agent/goal"][i],
                episode["map/edge"],
                pos_veh_lane,
                dir_veh_lane,
                map_id_veh_lane,
                pl_idx_veh_lane,
                pos_cyc_lane,
                dir_cyc_lane,
                pl_idx_cyc_lane,
                pos_road_edge,
                pl_idx_road_edge,
                dest_no_pred,
            )
```

should be replaced with:
`episode_reduced["agent/dest"][i] = 0`

Is that right?

**Comment by roydenwa** [comment]
@jakubmoscinski yes that's how I did it, I assume any dummy value should work.

**Comment by jakubmoscinski** [comment]
Thank you very much

**Comment by zhejz** [comment]
@roydenwa Thanks a lot for the help!

**Comment by Family-Liao** [comment]
Could you guys help me？I have a problem to evaluate av2 validation set. I open an issue on https://github.com/zhejz/HPTR/issues/13
Best wishes! Looking forward to your reply!
